package com.lsl.healthycamera.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lsl.healthycamera.entity.User;
import com.lsl.healthycamera.entity.MyDish;

import com.lsl.healthycamera.entity.UserDao;
import com.lsl.healthycamera.entity.MyDishDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig myDishDaoConfig;

    private final UserDao userDao;
    private final MyDishDao myDishDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        myDishDaoConfig = daoConfigMap.get(MyDishDao.class).clone();
        myDishDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        myDishDao = new MyDishDao(myDishDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(MyDish.class, myDishDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        myDishDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MyDishDao getMyDishDao() {
        return myDishDao;
    }

}
